from typing import Protocol
import numpy as np
from .models import VisionDetection

class VisionProvider(Protocol):
    @property
    def name(self) -> str: ...
    def initialize(self) -> None: ...
    def detect(self, *, frame: np.ndarray, frame_number: int, timestamp: float) -> VisionDetection: ...
    def reset(self) -> None: ...
    def shutdown(self) -> None: ...
